import "@styles";
import { lexend } from "@styles/fonts";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`e-book ${lexend.className}`}>{children}</body>
    </html>
  );
}
